set MATLAB=C:\Program Files\MATLAB\R2016b
"C:\Program Files\MATLAB\R2016b\bin\win64\gmake" -f can_spi_simple_block_bu.mk  GENERATE_ERT_S_FUNCTION=0 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=1 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 ISPROTECTINGMODEL=NOTPROTECTING
